import { SchemaDefinition, ValidationRules } from '@/app/lib/interface';
import { League, PredictionResult, User } from '@prisma/client';

type PredictionFormData = {
    sportType: string;
    league: string;
    homeTeam: string;
    awayTeam: string;
    tip: string;
    analysis?: string;
    odds?: number;
    result: PredictionResult;
    publishedAt: Date;
    createdBy?: User;
    isCustom: boolean
    customTitle?: string;
    customRange?: string;
    userId: string;
    isFree: boolean;
    league_rel?: League;
    validation?: ValidationRules
};


export const sportTypeOptions = [
    {
       label: 'Soccer', league: [
            { label: 'Premier League', value: 'Premier League' },
            { label: 'La Liga', value: 'La Liga' },
            { label: 'Bundesliga', value: 'Bundesliga' },
            { label: 'Serie A', value: 'Serie A' },
            { label: 'Ligue 1', value: 'Ligue 1' },
            { label: 'MLS', value: 'MLS' },
            { label: 'Eredivisie', value: 'Eredivisie' },
            { label: 'Primeira Liga', value: 'Primeira Liga' },
            { label: 'Championship', value: 'Championship' },
            { label: 'Scottish Premiership', value: 'Scottish Premiership' },
            { label: 'Super Lig', value: 'Super Lig' },
            { label: 'Russian Premier League', value: 'Russian Premier League' },
            { label: 'Chinese Super League', value: 'Chinese Super League' },
            { label: 'J1 League', value: 'J1 League' },
            { label: 'A-League', value: 'A-League' },
            { label: 'MLS Next Pro', value: 'MLS Next Pro' },
            { label: 'USL Championship', value: 'USL Championship' },
            { label: 'Liga MX', value: 'Liga MX' },
            { label: 'Copa Libertadores', value: 'Copa Libertadores' },
            { label: 'Copa Sudamericana', value: 'Copa Sudamericana' },
            { label: 'UEFA Champions League', value: 'UEFA Champions League' },
            { label: 'UEFA Europa League', value: 'UEFA Europa League' },
            { label: 'UEFA Conference League', value: 'UEFA Conference League' },
            { label: 'FIFA World Cup', value: 'FIFA World Cup' },
            { label: 'UEFA European Championship', value: 'UEFA European Championship' },
            { label: 'Copa America', value: 'Copa America' },
            { label: 'AFC Asian Cup', value: 'AFC Asian Cup' },
            { label: 'CONCACAF Gold Cup', value: 'CONCACAF Gold Cup' },
            { label: 'Africa Cup of Nations', value: 'Africa Cup of Nations' },
            { label: 'Oceania Nations Cup', value: 'Oceania Nations Cup' },
            { label: 'FIFA Club World Cup', value: 'FIFA Club World Cup' },
            { label: 'UEFA Super Cup', value: 'UEFA Super Cup' },
            { label: 'CONCACAF Champions League', value: 'CONCACAF Champions League' },
            { label: 'AFC Champions League', value: 'AFC Champions League' },
            { label: 'CAF Champions League', value: 'CAF Champions League' },
            { label: 'CONMEBOL Recopa', value: 'CONMEBOL Recopa' },
            { label: 'UEFA Youth League', value: 'UEFA Youth League' },
            { label: 'FIFA U-20 World Cup', value: 'FIFA U-20 World Cup' },
            { label: 'FIFA U-17 World Cup', value: 'FIFA U-17 World Cup' },
            { label: 'UEFA U21 Championship', value: 'UEFA U21 Championship' },
            { label: 'CONCACAF U20 Championship', value: 'CONCACAF U20 Championship' },
            { label: 'AFC U23 Asian Cup', value: 'AFC U23 Asian Cup' },
            { label: 'CAF U23 Africa Cup of Nations', value: 'CAF U23 Africa Cup of Nations' },
            { label: 'CONMEBOL U20 Championship', value: 'CONMEBOL U20 Championship' },
            { label: "FIFA Women's World Cup", value: "FIFA Women's World Cup" },
            { label: "UEFA Women's Champions League", value: "UEFA Women's Champions League" },
            { label: 'NWSL', value: 'NWSL' },
            { label: 'FA WSL', value: 'FA WSL' },
            { label: 'D1 Arkema', value: 'D1 Arkema' },
            { label: 'Frau Bundesliga', value: 'Frau Bundesliga' },
            { label: 'Primera Division Femenina', value: 'Primera Division Femenina' },
            { label: 'Liga F', value: 'Liga F' },
            { label: 'Serie A Femminile', value: 'Serie A Femminile' },
            { label: 'Damallsvenskan', value: 'Damallsvenskan' },
            { label: 'W-League', value: 'W-League' },
            { label: "FA Women's Championship", value: "FA Women's Championship" },
            { label: 'NWSL Challenge Cup', value: 'NWSL Challenge Cup' },
            { label: "UEFA Women's Euro", value: "UEFA Women's Euro" },
            { label: 'UEFA Nations League', value: 'UEFA Nations League' },
            { label: 'CONCACAF Nations League', value: 'CONCACAF Nations League' },
            { label: 'FIFA Confederations Cup', value: 'FIFA Confederations Cup' },
            { label: 'Primeira Liga (Portugal)', value: 'Primeira Liga (Portugal)' },
            { label: 'Liga NOS', value: 'Liga NOS' },
            { label: 'Belgian First Division A', value: 'Belgian First Division A' },
            { label: 'Austrian Bundesliga', value: 'Austrian Bundesliga' },
            { label: 'Swiss Super League', value: 'Swiss Super League' },
            { label: 'Norwegian Eliteserien', value: 'Norwegian Eliteserien' },
            { label: 'Danish Superliga', value: 'Danish Superliga' },
            { label: 'Swedish Allsvenskan', value: 'Swedish Allsvenskan' },
            { label: 'Finnish Veikkausliiga', value: 'Finnish Veikkausliiga' },
            { label: 'Czech First League', value: 'Czech First League' },
            { label: 'Slovak Super Liga', value: 'Slovak Super Liga' },
            { label: 'Hungarian NB I', value: 'Hungarian NB I' },
            { label: 'Polish Ekstraklasa', value: 'Polish Ekstraklasa' },
            { label: 'Romanian Liga I', value: 'Romanian Liga I' },
            { label: 'Bulgarian First League', value: 'Bulgarian First League' },
            { label: 'Croatian First League', value: 'Croatian First League' },
            { label: 'Serbian SuperLiga', value: 'Serbian SuperLiga' },
            { label: 'Ukrainian Premier League', value: 'Ukrainian Premier League' },
            { label: 'Greek Super League', value: 'Greek Super League' },
            { label: 'Israeli Premier League', value: 'Israeli Premier League' },
            { label: 'Cyprus First Division', value: 'Cyprus First Division' },
            { label: 'Maltese Premier League', value: 'Maltese Premier League' },
            { label: 'Icelandic Premier League', value: 'Icelandic Premier League' },
            { label: 'Faroese Premier League', value: 'Faroese Premier League' },
            { label: 'Argentine Primera División', value: 'Argentine Primera División' },
            { label: 'Brazilian Série A', value: 'Brazilian Série A' },
            { label: 'Chilean Primera División', value: 'Chilean Primera División' },
            { label: 'Colombian Primera A', value: 'Colombian Primera A' },
            { label: 'Ecuadorian Serie A', value: 'Ecuadorian Serie A' },
            { label: 'Peruvian Primera División', value: 'Peruvian Primera División' },
            { label: 'Uruguayan Primera División', value: 'Uruguayan Primera División' },
            { label: 'Paraguayan Primera División', value: 'Paraguayan Primera División' },
            { label: 'Bolivian Primera División', value: 'Bolivian Primera División' },
            { label: 'Venezuelan Primera División', value: 'Venezuelan Primera División' },
            { label: 'Canadian Premier League', value: 'Canadian Premier League' },
            { label: 'Mexican Liga de Expansión MX', value: 'Mexican Liga de Expansión MX' },
            { label: 'Costa Rican Primera División', value: 'Costa Rican Primera División' },
            { label: 'Guatemalan Liga Nacional', value: 'Guatemalan Liga Nacional' },
            { label: 'Honduran Liga Nacional', value: 'Honduran Liga Nacional' },
            { label: 'Salvadoran Primera División', value: 'Salvadoran Primera División' },
            { label: 'Nicaraguan Primera División', value: 'Nicaraguan Primera División' },
            { label: 'Panamanian Liga Panameña', value: 'Panamanian Liga Panameña' },
            { label: 'Jamaican Premier League', value: 'Jamaican Premier League' },
            { label: 'Trinidad and Tobago Pro League', value: 'Trinidad and Tobago Pro League' },
            { label: 'Indian Super League', value: 'Indian Super League' },
            { label: 'Indian I-League', value: 'Indian I-League' },
            { label: 'Saudi Pro League', value: 'Saudi Pro League' },
            { label: 'UAE Arabian Gulf League', value: 'UAE Arabian Gulf League' },
            { label: 'Qatar Stars League', value: 'Qatar Stars League' },
            { label: 'Iranian Persian Gulf Pro League', value: 'Iranian Persian Gulf Pro League' },
            { label: 'Iraqi Premier League', value: 'Iraqi Premier League' },
            { label: 'Korean K League 1', value: 'Korean K League 1' },
            { label: 'Korean K League 2', value: 'Korean K League 2' },
            { label: 'Thai League 1', value: 'Thai League 1' },
            { label: 'Vietnamese V.League 1', value: 'Vietnamese V.League 1' },
            { label: 'Malaysian Super League', value: 'Malaysian Super League' },
            { label: 'Singapore Premier League', value: 'Singapore Premier League' },
            { label: 'Indonesian Liga 1', value: 'Indonesian Liga 1' },
            { label: 'Philippine Football League', value: 'Philippine Football League' },
            { label: 'South African Premier Soccer League', value: 'South African Premier Soccer League' },
            { label: 'Egyptian Premier League', value: 'Egyptian Premier League' },
            { label: 'Moroccan Botola Pro', value: 'Moroccan Botola Pro' },
            { label: 'Tunisian Ligue Professionnelle 1', value: 'Tunisian Ligue Professionnelle 1' },
            { label: 'Algerian Ligue Professionnelle 1', value: 'Algerian Ligue Professionnelle 1' },
            { label: 'Ghanaian Premier League', value: 'Ghanaian Premier League' },
            { label: 'Nigerian Professional Football League', value: 'Nigerian Professional Football League' },
            { label: 'Kenyan Football Kenya Federation Premier League', value: 'Kenyan Football Kenya Federation Premier League' },
            { label: 'Tanzanian Premier League', value: 'Tanzanian Premier League' },
            { label: 'Ugandan Premier League', value: 'Ugandan Premier League' },
            { label: 'New Zealand Football Championship', value: 'New Zealand Football Championship' },
            { label: 'Fijian Premier League', value: 'Fijian Premier League' },
            { label: 'Tahitian Division Fédérale', value: 'Tahitian Division Fédérale' },
            { label: 'EFL League One', value: 'EFL League One' },
            { label: 'EFL League Two', value: 'EFL League Two' },
            { label: 'National League', value: 'National League' },
            { label: 'Serie B', value: 'Serie B' },
            { label: 'Serie C', value: 'Serie C' },
            { label: '2. Bundesliga', value: '2. Bundesliga' },
            { label: '3. Liga', value: '3. Liga' },
            { label: 'Ligue 2', value: 'Ligue 2' },
            { label: 'Segunda División', value: 'Segunda División' },
            { label: 'Eerste Divisie', value: 'Eerste Divisie' },
            { label: 'Liga Portugal 2', value: 'Liga Portugal 2' },
            { label: 'Scottish Championship', value: 'Scottish Championship' },
            { label: 'Scottish League One', value: 'Scottish League One' },
            { label: 'Scottish League Two', value: 'Scottish League Two' },
            { label: 'Copa del Rey', value: 'Copa del Rey' },
            { label: 'FA Cup', value: 'FA Cup' },
            { label: 'EFL Cup', value: 'EFL Cup' },
            { label: 'DFB-Pokal', value: 'DFB-Pokal' },
            { label: 'Coppa Italia', value: 'Coppa Italia' },
            { label: 'Coupe de France', value: 'Coupe de France' },
            { label: 'KNVB Beker', value: 'KNVB Beker' },
            { label: 'Taça de Portugal', value: 'Taça de Portugal' },
            { label: 'Scottish Cup', value: 'Scottish Cup' },
            { label: 'U.S. Open Cup', value: 'U.S. Open Cup' },
            { label: 'Copa América Femenina', value: 'Copa América Femenina' },
            { label: 'CONCACAF W Championship', value: 'CONCACAF W Championship' },
            { label: 'AFC Women\'s Asian Cup', value: 'AFC Women\'s Asian Cup' },
            { label: 'CAF Women\'s Championship', value: 'CAF Women\'s Championship' },
            { label: 'OFC Women\'s Nations Cup', value: 'OFC Women\'s Nations Cup' },
            { label: 'Jupiler Pro League', value: 'Jupiler Pro League' },
            { label: 'Super League 1', value: 'Super League 1' },
            { label: 'Liga I', value: 'Liga I' }, 
            { label: 'HNL', value: 'HNL' }, 
            { label: 'Fortuna Liga', value: 'Fortuna Liga' },
            { label: 'Premijer Liga', value: 'Premijer Liga' }, 
            { label: 'Macedonian First League', value: 'Macedonian First League' },
            { label: 'Albanian Superliga', value: 'Albanian Superliga' },
            { label: 'Estonian Meistriliiga', value: 'Estonian Meistriliiga' },
            { label: 'Latvian Higher League', value: 'Latvian Higher League' },
            { label: 'Lithuanian A Lyga', value: 'Lithuanian A Lyga' },
            { label: 'Armenian Premier League', value: 'Armenian Premier League' },
            { label: 'Georgian Erovnuli Liga', value: 'Georgian Erovnuli Liga' },
            { label: 'Azerbaijani Premier League', value: 'Azerbaijani Premier League' },
            { label: 'Kazakhstani Premier League', value: 'Kazakhstani Premier League' },
            { label: 'Moldovan Super Liga', value: 'Moldovan Super Liga' },
            { label: 'Belarusian Premier League', value: 'Belarusian Premier League' },
            { label: 'Uzbekistan Super League', value: 'Uzbekistan Super League' },
            { label: 'Afghanistan Premier League', value: 'Afghanistan Premier League' },
            { label: 'Bangladesh Premier League', value: 'Bangladesh Premier League' },
            { label: 'Myanmar National League', value: 'Myanmar National League' },
            { label: 'Cambodian League', value: 'Cambodian League' },
            { label: 'Laos Premier League', value: 'Laos Premier League' },
            { label: 'Bhutan Premier League', value: 'Bhutan Premier League' },
            { label: 'Maldivian Premier League', value: 'Maldivian Premier League' },
            { label: 'Sri Lankan Premier League', value: 'Sri Lankan Premier League' },
            { label: 'Nepal Super League', value: 'Nepal Super League' },
            { label: 'Libyan Premier League', value: 'Libyan Premier League' },
            { label: 'Sudanese Premier League', value: 'Sudanese Premier League' },
            { label: 'Ethiopian Premier League', value: 'Ethiopian Premier League' },
            { label: 'Rwandan Premier League', value: 'Rwandan Premier League' },
            { label: 'Burundian Premier League', value: 'Burundian Premier League' },
            { label: 'Congolese Premier League', value: 'Congolese Premier League' },
            { label: 'Cameroonian Elite One', value: 'Cameroonian Elite One' },
            { label: 'Ivorian Ligue 1', value: 'Ivorian Ligue 1' },
            { label: 'Senegalese Ligue 1', value: 'Senegalese Ligue 1' },
            { label: 'Malian Première Division', value: 'Malian Première Division' },
            { label: 'Burkinabé Premier League', value: 'Burkinabé Premier League' },
            { label: 'Nigerien Championnat National', value: 'Nigerien Championnat National' },
            { label: 'Chadian Premier League', value: 'Chadian Premier League' },
            { label: 'Central African Premier League', value: 'Central African Premier League' },
            { label: 'Gabonese Championnat National D1', value: 'Gabonese Championnat National D1' },
            { label: 'Equatorial Guinea Primera División', value: 'Equatorial Guinea Primera División' },
            { label: 'São Tomé and Príncipe Championship', value: 'São Tomé and Príncipe Championship' },
            { label: 'Cape Verdean Premier League', value: 'Cape Verdean Premier League' },
            { label: 'Guinea-Bissau Premier League', value: 'Guinea-Bissau Premier League' },
            { label: 'Sierra Leone Premier League', value: 'Sierra Leone Premier League' },
            { label: 'Liberian Premier League', value: 'Liberian Premier League' },
            { label: 'Gambian GFA League', value: 'Gambian GFA League' },
            { label: 'Mauritanian Premier League', value: 'Mauritanian Premier League' },
            { label: 'Mauritius Premier League', value: 'Mauritius Premier League' },
            { label: 'Seychelles Premier League', value: 'Seychelles Premier League' },
            { label: 'Comoros Premier League', value: 'Comoros Premier League' },
            { label: 'Madagascar THB Champions League', value: 'Madagascar THB Champions League' },
            { label: 'Réunion Régional 1', value: 'Réunion Régional 1' },
            { label: 'Mayotte Ligue de Football', value: 'Mayotte Ligue de Football' },
            { label: 'Tanzanian Premier League', value: 'Tanzanian Premier League' },
            { label: 'Zambian Super League', value: 'Zambian Super League' },
            { label: 'Zimbabwe Premier Soccer League', value: 'Zimbabwe Premier Soccer League' },
            { label: 'Angolan Girabola', value: 'Angolan Girabola' },
            { label: 'Mozambican Moçambola', value: 'Mozambican Moçambola' },
            { label: 'Namibian Premier League', value: 'Namibian Premier League' },
            { label: 'Botswana Premier League', value: 'Botswana Premier League' },
            { label: 'Lesotho Premier League', value: 'Lesotho Premier League' },
            { label: 'Eswatini Premier League', value: 'Eswatini Premier League' },
            { label: 'Bermudian Premier Division', value: 'Bermudian Premier Division' },
            { label: 'Barbados Premier League', value: 'Barbados Premier League' },
            { label: 'Dominican Republic Liga Mayor', value: 'Dominican Republic Liga Mayor' },
            { label: 'Haiti Championnat National', value: 'Haiti Championnat National' },
            { label: 'Puerto Rico Liga Mayor', value: 'Puerto Rico Liga Mayor' },
            { label: 'Martinique Championnat National', value: 'Martinique Championnat National' },
            { label: 'Guadeloupe Championnat National', value: 'Guadeloupe Championnat National' },
            { label: 'French Guiana Championnat National', value: 'French Guiana Championnat National' },
            { label: 'Suriname Hoofdklasse', value: 'Suriname Hoofdklasse' },
            { label: 'Guyana Elite League', value: 'Guyana Elite League' },
            { label: 'Belize Premier League', value: 'Belize Premier League' },
            { label: 'Curacao Sekshon Pagá', value: 'Curacao Sekshon Pagá' },
            { label: 'Aruba Division di Honor', value: 'Aruba Division di Honor' },
            { label: 'Saint Vincent Premier Division', value: 'Saint Vincent Premier Division' },
            { label: 'Grenada Premier Division', value: 'Grenada Premier Division' },
            { label: 'Saint Lucia Gold Division', value: 'Saint Lucia Gold Division' },
            { label: 'Dominica Premier League', value: 'Dominica Premier League' },
            { label: 'Antigua and Barbuda Premier Division', value: 'Antigua and Barbuda Premier Division' },
            { label: 'Saint Kitts and Nevis Premier League', value: 'Saint Kitts and Nevis Premier League' },   
            { label: 'Cook Islands Round Cup', value: 'Cook Islands Round Cup' },
            { label: 'Samoa National League', value: 'Samoa National League' },
            { label: 'Tonga Major League', value: 'Tonga Major League' },
            { label: 'Vanuatu Premier League', value: 'Vanuatu Premier League' },
            { label: 'Solomon Islands S-League', value: 'Solomon Islands S-League' },
            { label: 'Papua New Guinea National Soccer League', value: 'Papua New Guinea National Soccer League' },
            { label: 'New Caledonia Super Ligue', value: 'New Caledonia Super Ligue' },
            { label: 'Palau Soccer League', value: 'Palau Soccer League' },
            { label: 'Federated States of Micronesia League', value: 'Federated States of Micronesia League' },
            { label: 'Marshall Islands Premier League', value: 'Marshall Islands Premier League' },
            { label: 'Kiribati National Championship', value: 'Kiribati National Championship' },
            { label: 'Nauru Premier League', value: 'Nauru Premier League' },
            { label: 'Tuvalu A-Division', value: 'Tuvalu A-Division' }, 
            { label: 'Coupe de la Ligue', value: 'Coupe de la Ligue' },
            { label: 'Copa Italia Serie C', value: 'Copa Italia Serie C' },
            { label: 'Copa Catalunya', value: 'Copa Catalunya' },
            { label: 'Welsh Cup', value: 'Welsh Cup' },
            { label: 'Northern Ireland Cup', value: 'Northern Ireland Cup' },
            { label: 'Irish Cup', value: 'Irish Cup' },
            { label: 'Community Shield', value: 'Community Shield' }, 
            { label: 'Supercopa de España', value: 'Supercopa de España' }, 
            { label: 'Supercoppa Italiana', value: 'Supercoppa Italiana' },
            { label: 'DFL-Supercup', value: 'DFL-Supercup' }, 
            { label: 'Trophée des Champions', value: 'Trophée des Champions' }, 
            { label: 'Johan Cruyff Shield', value: 'Johan Cruyff Shield' }, 
            { label: 'FIFA U-19 Women\'s World Cup', value: 'FIFA U-19 Women\'s World Cup' },
            { label: 'FIFA U-16 Women\'s World Cup', value: 'FIFA U-16 Women\'s World Cup' },
            { label: 'UEFA U19 Championship', value: 'UEFA U19 Championship' },
            { label: 'UEFA U17 Championship', value: 'UEFA U17 Championship' },
            { label: 'CONMEBOL U17 Championship', value: 'CONMEBOL U17 Championship' },
            { label: 'AFC U19 Championship', value: 'AFC U19 Championship' },
            { label: 'AFC U16 Championship', value: 'AFC U16 Championship' },
            { label: 'CAF U20 Africa Cup of Nations', value: 'CAF U20 Africa Cup of Nations' },
            { label: 'CAF U17 Africa Cup of Nations', value: 'CAF U17 Africa Cup of Nations' },
            { label: 'CONCACAF U17 Championship', value: 'CONCACAF U17 Championship' },
            { label: 'OFC U20 Championship', value: 'OFC U20 Championship' },
            { label: 'OFC U16 Championship', value: 'OFC U16 Championship' }
        ]
    },
    {
        label: 'Basketball', league: [
            { label: 'NBA', value: 'NBA' },
            { label: 'EuroLeague', value: 'EuroLeague' },
            { label: 'NBL', value: 'NBL' },
            { label: 'WNBA', value: 'WNBA' },
            { label: 'CBA', value: 'CBA' },
            { label: 'Liga ACB', value: 'Liga ACB' },
            { label: 'Liga Nacional', value: 'Liga Nacional' },
            { label: 'Lega Basket Serie A', value: 'Lega Basket Serie A' },
            { label: 'Basketball Bundesliga', value: 'Basketball Bundesliga' },
            { label: 'French Jeep Elite', value: 'French Jeep Elite' },
            { label: 'VTB United League', value: 'VTB United League' },
            { label: 'Adriatic League', value: 'Adriatic League' },
            { label: 'Basketball Champions League', value: 'Basketball Champions League' },
            { label: 'FIBA EuroCup', value: 'FIBA EuroCup' },
            { label: 'FIBA Basketball World Cup', value: 'FIBA Basketball World Cup' },
            { label: 'Olympic Basketball Tournament', value: 'Olympic Basketball Tournament' },
            { label: 'FIBA Women\'s Basketball World Cup', value: 'FIBA Women\'s Basketball World Cup' },
            { label: 'WNBA Finals', value: 'WNBA Finals' },

        ]
    },
    {
        label: 'Tennis', league: [
            { label: 'ATP Tour', value: 'ATP Tour' },
            { label: 'WTA Tour', value: 'WTA Tour' },
            { label: 'Grand Slam Tournaments', value: 'Grand Slam Tournaments' },
            { label: 'Davis Cup', value: 'Davis Cup' },
            { label: 'Fed Cup', value: 'Fed Cup' },
            { label: 'Olympic Tennis Tournament', value: 'Olympic Tennis Tournament' },
            { label: 'ATP Challenger Tour', value: 'ATP Challenger Tour' },
            { label: 'WTA 125K Series', value: 'WTA 125K Series' },
            { label: 'ITF World Tennis Tour', value: 'ITF World Tennis Tour' },
            { label: 'Hopman Cup', value: 'Hopman Cup' },
            { label: 'Laver Cup', value: 'Laver Cup' },
            { label: 'Next Gen ATP Finals', value: 'Next Gen ATP Finals' },
            { label: 'WTA Finals', value: 'WTA Finals' },
            { label: 'ATP Finals', value: 'ATP Finals' },
            { label: 'Davis Cup Finals', value: 'Davis Cup Finals' },
            { label: 'Fed Cup Finals', value: 'Fed Cup Finals' },
            { label: 'ATP Masters 1000', value: 'ATP Masters 1000' },
            { label: 'WTA Premier Mandatory', value: 'WTA Premier Mandatory' },
            { label: 'WTA Premier 5', value: 'WTA Premier 5' },
            { label: 'ATP 500 Series', value: 'ATP 500 Series' },
            { label: 'WTA International', value: 'WTA International' },
            { label: 'Challenger Tour Finals', value: 'Challenger Tour Finals' },
        ]
    },
    {
        label: 'American Football', league: [
            { label: 'NFL', value: 'NFL' },
            { label: 'CFL', value: 'CFL' },
            { label: 'XFL', value: 'XFL' },
            { label: 'USFL', value: 'USFL' },
            { label: 'NCAA Division I FBS', value: 'NCAA Division I FBS' },
            { label: 'NCAA Division I FCS', value: 'NCAA Division I FCS' },
            { label: 'NCAA Division II', value: 'NCAA Division II' },
            { label: 'NCAA Division III', value: 'NCAA Division III' },
            { label: 'NAIA Football', value: 'NAIA Football' },
            { label: 'European League of Football', value: 'European League of Football' },
            { label: 'LFA Mexico', value: 'LFA Mexico' },
            { label: 'Liga de Fútbol Americano Profesional', value: 'Liga de Fútbol Americano Profesional' },
            { label: 'Liga Nacional de Fútbol Americano', value: 'Liga Nacional de Fútbol Americano' },
            { label: 'Liga Argentina de Fútbol Americano', value: 'Liga Argentina de Fútbol Americano' },
            { label: 'Liga Portuguesa de Futebol Americano', value: 'Liga Portuguesa de Futebol Americano' },
            { label: 'Liga Española de Fútbol Americano', value: 'Liga Española de Fútbol Americano' },
            { label: 'Liga Francesa de Football Américain', value: 'Liga Francesa de Football Américain' },
            { label: 'Liga Italiana di Football Americano', value: 'Liga Italiana di Football Americano' },
            { label: 'Liga Alemana de Football Americano', value: 'Liga Alemana de Football Americano' },
            { label: 'Liga Británica de Fútbol Americano', value: 'Liga Británica de Fútbol Americano' },
            { label: 'Liga Sueca de Fútbol Americano', value: 'Liga Sueca de Fútbol Americano' },
            { label: 'Liga Danesa de Fútbol Americano', value: 'Liga Danesa de Fútbol Americano' },
            { label: 'Liga Finlandesa de Fútbol Americano', value: 'Liga Finlandesa de Fútbol Americano' },
            { label: 'Liga Noruega de Fútbol Americano', value: 'Liga Noruega de Fútbol Americano' },
        ]
    },
    {
        label: 'Baseball', league: [
            { label: 'MLB', value: 'MLB' },
            { label: 'Nippon Professional Baseball', value: 'Nippon Professional Baseball' },
            { label: 'Korea Baseball Organization', value: 'Korea Baseball Organization' },
            { label: 'Chinese Professional Baseball League', value: 'Chinese Professional Baseball League' },
            { label: 'Liga Mexicana de Béisbol', value: 'Liga Mexicana de Béisbol' },
            { label: 'Liga Venezolana de Béisbol Profesional', value: 'Liga Venezolana de Béisbol Profesional' },
            { label: 'Liga Dominicana de Béisbol Profesional', value: 'Liga Dominicana de Béisbol Profesional' },
            { label: 'Liga de Béisbol Profesional Roberto Clemente', value: 'Liga de Béisbol Profesional Roberto Clemente' },
            { label: 'Australian Baseball League', value: 'Australian Baseball League' },
            { label: 'European Baseball Championship', value: 'European Baseball Championship' },
            { label: 'World Baseball Classic', value: 'World Baseball Classic' },
            { label: 'Little League World Series', value: 'Little League World Series' },
            { label: 'College World Series', value: 'College World Series' },
            { label: 'Cape Cod Baseball League', value: 'Cape Cod Baseball League' },
            { label: 'Atlantic League', value: 'Atlantic League' },
            { label: 'American Association', value: 'American Association' },
            { label: 'Frontier League', value: 'Frontier League' },
            { label: 'Pioneer League', value: 'Pioneer League' },
            { label: 'Pacific Association', value: 'Pacific Association' },
            { label: 'Liga de Béisbol Profesional de Panamá', value: 'Liga de Béisbol Profesional de Panamá' },
            { label: 'Liga de Béisbol Profesional de Colombia', value: 'Liga de Béisbol Profesional de Colombia' },
            { label: 'Liga de Béisbol Profesional de Nicaragua', value: 'Liga de Béisbol Profesional de Nicaragua' },
            { label: 'Liga de Béisbol Profesional de Guatemala', value: 'Liga de Béisbol Profesional de Guatemala' },
        ]
    },
    {
        label: 'Hockey', league: [
            { label: 'NHL', value: 'NHL' },
            { label: 'KHL', value: 'KHL' },
            { label: 'AHL', value: 'AHL' },
            { label: 'EIHL', value: 'EIHL' },
            { label: 'SHL', value: 'SHL' },
            { label: 'Liiga', value: 'Liiga' },
            { label: 'DEL', value: 'DEL' },
            { label: 'NLA', value: 'NLA' },
            { label: 'Czech Extraliga', value: 'Czech Extraliga' },
            { label: 'Swiss League', value: 'Swiss League' },
            { label: 'IIHF World Championship', value: 'IIHF World Championship' },
            { label: 'Olympic Ice Hockey Tournament', value: 'Olympic Ice Hockey Tournament' },
            { label: 'World Junior Ice Hockey Championships', value: 'World Junior Ice Hockey Championships' },
            { label: 'Spengler Cup', value: 'Spengler Cup' },
            { label: 'CHL Champions Hockey League', value: 'CHL Champions Hockey League' },
            { label: 'NCAA Division I Ice Hockey', value: 'NCAA Division I Ice Hockey' },
            { label: 'USHL United States Hockey League', value: 'USHL United States Hockey League' },
            { label: 'OHL Ontario Hockey League', value: 'OHL Ontario Hockey League' },
            { label: 'WHL Western Hockey League', value: 'WHL Western Hockey League' },
            { label: 'QMJHL Quebec Major Junior Hockey League', value: 'QMJHL Quebec Major Junior Hockey League' },
            { label: 'ECHL East Coast Hockey League', value: 'ECHL East Coast Hockey League' },
            { label: 'SPHL Southern Professional Hockey League', value: 'SPHL Southern Professional Hockey League' },
            { label: 'FHL Federal Hockey League', value: 'FHL Federal Hockey League' },
            { label: 'LNAH Ligue Nord-Américaine de Hockey', value: 'LNAH Ligue Nord-Américaine de Hockey' },
        ]
    },
    {
        label: 'Rugby', league: [
            { label: 'Rugby Union', value: 'Rugby Union' },
            { label: 'Rugby League', value: 'Rugby League' },
            { label: 'Super Rugby', value: 'Super Rugby' },
            { label: 'Top 14', value: 'Top 14' },
            { label: 'Premiership Rugby', value: 'Premiership Rugby' },
            { label: 'Pro14', value: 'Pro14' },
            { label: 'Major League Rugby', value: 'Major League Rugby' },
            { label: 'European Rugby Champions Cup', value: 'European Rugby Champions Cup' },
            { label: 'European Rugby Challenge Cup', value: 'European Rugby Challenge Cup' },
            { label: 'Six Nations Championship', value: 'Six Nations Championship' },
            { label: 'Rugby World Cup', value: 'Rugby World Cup' },
            { label: 'British and Irish Lions Tour', value: 'British and Irish Lions Tour' },
            { label: 'Rugby Championship', value: 'Rugby Championship' },
            { label: 'Currie Cup', value: 'Currie Cup' },
            { label: 'Mitre 10 Cup', value: 'Mitre 10 Cup' },
            { label: 'National Rugby Championship', value: 'National Rugby Championship' },
            { label: 'European Rugby Sevens Series', value: 'European Rugby Sevens Series' },
            { label: 'World Rugby Sevens Series', value: 'World Rugby Sevens Series' },
            { label: 'Olympic Rugby Sevens Tournament', value: 'Olympic Rugby Sevens Tournament' },
            { label: 'Rugby Americas North Championship', value: 'Rugby Americas North Championship' },
            { label: 'Asia Rugby Championship', value: 'Asia Rugby Championship' },
            { label: 'Africa Cup', value: 'Africa Cup' },
            { label: 'Pacific Nations Cup', value: 'Pacific Nations Cup' },
            { label: 'European Nations Cup', value: 'European Nations Cup' },
            { label: 'Rugby Europe Championship', value: 'Rugby Europe Championship' },
            { label: 'Rugby Americas South Championship', value: 'Rugby Americas South Championship' },
        ]
    },
    {
        label: 'Cricket', league: [
            { label: 'Indian Premier League', value: 'Indian Premier League' },
            { label: 'Big Bash League', value: 'Big Bash League' },
            { label: 'Pakistan Super League', value: 'Pakistan Super League' },
            { label: 'Caribbean Premier League', value: 'Caribbean Premier League' },
            { label: 'Vitality Blast', value: 'Vitality Blast' },
            { label: 'County Championship', value: 'County Championship' },
            { label: 'Sheffield Shield', value: 'Sheffield Shield' },
            { label: 'Ranji Trophy', value: 'Ranji Trophy' },
            { label: 'Duleep Trophy', value: 'Duleep Trophy' },
            { label: 'Deodhar Trophy', value: 'Deodhar Trophy' },
            { label: 'Syed Mushtaq Ali Trophy', value: 'Syed Mushtaq Ali Trophy' },
            { label: 'Vijay Hazare Trophy', value: 'Vijay Hazare Trophy' },
            { label: 'ICC Cricket World Cup', value: 'ICC Cricket World Cup' },
            { label: 'ICC T20 World Cup', value: 'ICC T20 World Cup' },
            { label: 'ICC Champions Trophy', value: 'ICC Champions Trophy' },
            { label: 'Asia Cup', value: 'Asia Cup' },
            { label: 'Bilateral Series', value: 'Bilateral Series' },
            { label: 'Test Series', value: 'Test Series' },
            { label: 'ODI Series', value: 'ODI Series' },
            { label: 'T20I Series', value: 'T20I Series' },
            { label: 'Domestic T20 Leagues', value: 'Domestic T20 Leagues' },
            { label: 'Women\'s Cricket', value: 'Women\'s Cricket' },
            { label: 'Women\'s T20 Leagues', value: 'Women\'s T20 Leagues' },
            { label: 'Women\'s ODI Series', value: 'Women\'s ODI Series' },
            { label: 'Women\'s Test Series', value: 'Women\'s Test Series' },

        ]
    },
    {
        label: 'Volleyball', league: [
            { label: 'FIVB Volleyball World Championship', value: 'FIVB Volleyball World Championship' },
            { label: 'FIVB Volleyball Nations League', value: 'FIVB Volleyball Nations League' },
            { label: 'FIVB Beach Volleyball World Tour', value: 'FIVB Beach Volleyball World Tour' },
            { label: 'AVP Pro Beach Volleyball Tour', value: 'AVP Pro Beach Volleyball Tour' },
            { label: 'CEV Champions League', value: 'CEV Champions League' },
            { label: 'CEV Cup', value: 'CEV Cup' },
            { label: 'CEV Challenge Cup', value: 'CEV Challenge Cup' },
            { label: 'NCAA Division I Volleyball Championship', value: 'NCAA Division I Volleyball Championship' },
            { label: 'NCAA Division II Volleyball Championship', value: 'NCAA Division II Volleyball Championship' },
            { label: 'NCAA Division III Volleyball Championship', value: 'NCAA Division III Volleyball Championship' },
            { label: 'AVCA Collegiate Beach Volleyball Championship', value: 'AVCA Collegiate Beach Volleyball Championship' },
            { label: 'FIVB Women\'s Volleyball World Championship', value: 'FIVB Women\'s Volleyball World Championship' },
            { label: 'FIVB Women\'s Volleyball Nations League', value: 'FIVB Women\'s Volleyball Nations League' },
            { label: 'FIVB Women\'s Beach Volleyball World Tour', value: 'FIVB Women\'s Beach Volleyball World Tour' },
            { label: 'AVP Women\'s Pro Beach Volleyball Tour', value: 'AVP Women\'s Pro Beach Volleyball Tour' },
            { label: 'FIVB U21 Volleyball World Championship', value: 'FIVB U21 Volleyball World Championship' },
            { label: 'FIVB U19 Volleyball World Championship', value: 'FIVB U19 Volleyball World Championship' },
            { label: 'FIVB U23 Volleyball World Championship', value: 'FIVB U23 Volleyball World Championship' },
            { label: 'FIVB U21 Beach Volleyball World Championship', value: 'FIVB U21 Beach Volleyball World Championship' },
            { label: 'FIVB U19 Beach Volleyball World Championship', value: 'FIVB U19 Beach Volleyball World Championship' },
        ]
    },
    {
        label: 'Handball', league: [
            { label: 'EHF Champions League', value: 'EHF Champions League' },
            { label: 'EHF Cup', value: 'EHF Cup' },
            { label: 'EHF Challenge Cup', value: 'EHF Challenge Cup' },
            { label: 'IHF World Championship', value: 'IHF World Championship' },
            { label: 'IHF World Handball Championship', value: 'IHF World Handball Championship' },
            { label: 'Olympic Handball Tournament', value: 'Olympic Handball Tournament' },
            { label: 'European Handball Championship', value: 'European Handball Championship' },
            { label: 'Pan American Handball Championship', value: 'Pan American Handball Championship' },
            { label: 'Asian Handball Championship', value: 'Asian Handball Championship' },
            { label: 'African Handball Championship', value: 'African Handball Championship' },
            { label: 'North American and Caribbean Handball Championship', value: 'North American and Caribbean Handball Championship' },
            { label: 'Handball Bundesliga', value: 'Handball Bundesliga' },
            { label: 'Ligue Nationale de Handball', value: 'Ligue Nationale de Handball' },
            { label: 'Liga ASOBAL', value: 'Liga ASOBAL' },
            { label: 'Danish Handball League', value: 'Danish Handball League' },
            { label: 'Swedish Handbollsligan', value: 'Swedish Handbollsligan' },
        ]
    },
    {
        label: 'Mixed', league: [
            { label: 'Mixed Martial Arts', value: 'Mixed Martial Arts' },
            { label: 'Boxing', value: 'Boxing' },
            { label: 'Wrestling', value: 'Wrestling' },
            { label: 'Judo', value: 'Judo' },
            { label: 'Taekwondo', value: 'Taekwondo' },
            { label: 'Karate', value: 'Karate' },
            { label: 'Kickboxing', value: 'Kickboxing' },
            { label: 'Muay Thai', value: 'Muay Thai' },
            { label: 'Brazilian Jiu-Jitsu', value: 'Brazilian Jiu-Jitsu' },
            { label: 'Sambo', value: 'Sambo' },
            { label: 'Krav Maga', value: 'Krav Maga' },
            { label: 'Capoeira', value: 'Capoeira' },
            { label: 'Aikido', value: 'Aikido' },
            { label: 'Hapkido', value: 'Hapkido' },
            { label: 'Wing Chun', value: 'Wing Chun' },
            { label: 'Sanda', value: 'Sanda' },
            { label: 'Lethwei', value: 'Lethwei' },
            { label: 'Savate', value: 'Savate' },
            { label: 'Pencak Silat', value: 'Pencak Silat' },
            { label: 'Systema', value: 'Systema' },
            { label: 'Ninjutsu', value: 'Ninjutsu' },
            { label: 'Jeet Kune Do', value: 'Jeet Kune Do' },
            { label: 'Combat Sambo', value: 'Combat Sambo' },
        ]
    },
    {
        label: 'Boxing', league: [
            { label: 'WBC', value: 'WBC' },
            { label: 'WBA', value: 'WBA' },
            { label: 'IBF', value: 'IBF' },
            { label: 'WBO', value: 'WBO' },
            { label: 'IBO', value: 'IBO' },
            { label: 'The Ring Magazine', value: 'The Ring Magazine' },
            { label: 'World Boxing Super Series', value: 'World Boxing Super Series' },


        ]
    },
    {
        label: 'Golf', league: [
            { label: 'PGA Tour', value: 'PGA Tour' },
            { label: 'European Tour', value: 'European Tour' },
            { label: 'LPGA Tour', value: 'LPGA Tour' },
            { label: 'Champions Tour', value: 'Champions Tour' },
            { label: 'Asian Tour', value: 'Asian Tour' },
            { label: 'Sunshine Tour', value: 'Sunshine Tour' },
            { label: 'Japan Golf Tour', value: 'Japan Golf Tour' },
            { label: 'Ladies European Tour', value: 'Ladies European Tour' },
            { label: 'Korn Ferry Tour', value: 'Korn Ferry Tour' },
            { label: 'Omega Dubai Desert Classic', value: 'Omega Dubai Desert Classic' },
            { label: 'The Masters Tournament', value: 'The Masters Tournament' },
            { label: 'U.S. Open Championship', value: 'U.S. Open Championship' },
            { label: 'The Open Championship', value: 'The Open Championship' },
            { label: 'PGA Championship', value: 'PGA Championship' },
            { label: 'Ryder Cup', value: 'Ryder Cup' },
            { label: 'Solheim Cup', value: 'Solheim Cup' },
            { label: 'President\'s Cup', value: 'President\'s Cup' },
            { label: 'Olympic Golf Tournament', value: 'Olympic Golf Tournament' },
            { label: 'World Golf Championships', value: 'World Golf Championships' },
            { label: 'FedEx Cup Playoffs', value: 'FedEx Cup Playoffs' },


        ]
    },
    {
        label: 'Motorsport', league: [
            { label: 'Formula 1', value: 'Formula 1' },
            { label: 'MotoGP', value: 'MotoGP' },
            { label: 'NASCAR Cup Series', value: 'NASCAR Cup Series' },
            { label: 'IndyCar Series', value: 'IndyCar Series' },
            { label: 'World Rally Championship', value: 'World Rally Championship' },
            { label: 'FIA World Endurance Championship', value: 'FIA World Endurance Championship' },
            { label: 'FIA Formula E Championship', value: 'FIA Formula E Championship' },
            { label: 'Supercars Championship', value: 'Supercars Championship' },
            { label: 'DTM Deutsche Tourenwagen Masters', value: 'DTM Deutsche Tourenwagen Masters' },
            { label: 'British Touring Car Championship', value: 'British Touring Car Championship' },
            { label: 'IMSA WeatherTech SportsCar Championship', value: 'IMSA WeatherTech SportsCar Championship' },
            { label: 'Le Mans 24 Hours', value: 'Le Mans 24 Hours' },
            { label: 'Monaco Grand Prix', value: 'Monaco Grand Prix' },
            { label: 'Indianapolis 500', value: 'Indianapolis 500' },
            { label: 'Daytona 500', value: 'Daytona 500' },
            { label: 'Tour de France Cycliste', value: 'Tour de France Cycliste' },
            { label: 'Vuelta a España', value: 'Vuelta a España' },
            { label: 'Giro d\'Italia', value: 'Giro d\'Italia' },
        ]
    },
    {
        label: 'Esports', league: [
            { label: 'League of Legends', value: 'League of Legends' },
            { label: 'Dota 2', value: 'Dota 2' },
            { label: 'Counter-Strike: Global Offensive', value: 'Counter-Strike: Global Offensive' },
            { label: 'Overwatch', value: 'Overwatch' },
            { label: 'Valorant', value: 'Valorant' },
            { label: 'Call of Duty', value: 'Call of Duty' },
            { label: 'FIFA', value: 'FIFA' },
            { label: 'PUBG', value: 'PUBG' },
            { label: 'Apex Legends', value: 'Apex Legends' },
            { label: 'Rainbow Six Siege', value: 'Rainbow Six Siege' },
            { label: 'StarCraft II', value: 'StarCraft II' },
            { label: 'Hearthstone', value: 'Hearthstone' },
            { label: 'Rocket League', value: 'Rocket League' },
            { label: 'Smite', value: 'Smite' },
            { label: 'World of Warcraft', value: 'World of Warcraft' },
            { label: 'Street Fighter V', value: 'Street Fighter V' },
            { label: 'Tekken 7', value: 'Tekken 7' },
        ]
    },
    {
        label: 'Table Tennis', league: [
            { label: 'ITTF World Tour', value: 'ITTF World Tour' },
            { label: 'ITTF World Championships', value: 'ITTF World Championships' },
            { label: 'ITTF World Cup', value: 'ITTF World Cup' },
            { label: 'European Table Tennis Championships', value: 'European Table Tennis Championships' },
            { label: 'Asian Table Tennis Championships', value: 'Asian Table Tennis Championships' },
            { label: 'Pan American Table Tennis Championships', value: 'Pan American Table Tennis Championships' },
            { label: 'African Table Tennis Championships', value: 'African Table Tennis Championships' },
            { label: 'Oceania Table Tennis Championships', value: 'Oceania Table Tennis Championships' },
            { label: 'National Table Tennis Leagues', value: 'National Table Tennis Leagues' },
            { label: 'Chinese Super League', value: 'Chinese Super League' },
            { label: 'German Bundesliga', value: 'German Bundesliga' },
            { label: 'Japanese T.League', value: 'Japanese T.League' },
            { label: 'Korean Table Tennis League', value: 'Korean Table Tennis League' },
            { label: 'French Table Tennis League', value: 'French Table Tennis League' },
            { label: 'Spanish Table Tennis League', value: 'Spanish Table Tennis League' },
            { label: 'Italian Table Tennis League', value: 'Italian Table Tennis League' },
            { label: 'Russian Table Tennis League', value: 'Russian Table Tennis League' },
            { label: 'Swedish Table Tennis League', value: 'Swedish Table Tennis League' },
            { label: 'English Table Tennis League', value: 'English Table Tennis League' },
            { label: 'International Table Tennis Federation (ITTF)', value: 'International Table Tennis Federation (ITTF)' },
        ]
    },
    {
        label: 'Badminton', league: [
            { label: 'BWF World Tour', value: 'BWF World Tour' },
            { label: 'BWF World Championships', value: 'BWF World Championships' },
            { label: 'BWF Thomas Cup', value: 'BWF Thomas Cup' },
            { label: 'BWF Uber Cup', value: 'BWF Uber Cup' },
            { label: 'BWF Sudirman Cup', value: 'BWF Sudirman Cup' },
            { label: 'BWF All England Open Badminton Championships', value: 'BWF All England Open Badminton Championships' },
            { label: 'BWF Malaysia Open', value: 'BWF Malaysia Open' },
            { label: 'BWF Indonesia Open', value: 'BWF Indonesia Open' },
            { label: 'BWF China Open', value: 'BWF China Open' },
            { label: 'BWF Japan Open', value: 'BWF Japan Open' },
            { label: 'BWF Korea Open', value: 'BWF Korea Open' },
            { label: 'BWF Denmark Open', value: 'BWF Denmark Open' },
            { label: 'BWF French Open', value: 'BWF French Open' },
            { label: 'BWF India Open', value: 'BWF India Open' },
            { label: 'BWF Singapore Open', value: 'BWF Singapore Open' },
            { label: 'BWF Thailand Open', value: 'BWF Thailand Open' },
            { label: 'BWF Hong Kong Open', value: 'BWF Hong Kong Open' },
            { label: 'BWF Australia Open', value: 'BWF Australia Open' },
            { label: 'BWF New Zealand Open', value: 'BWF New Zealand Open' },
            { label: 'BWF European Championships', value: 'BWF European Championships' },
            { label: 'BWF Pan American Championships', value: 'BWF Pan American Championships' },
            { label: 'BWF African Championships', value: 'BWF African Championships' },
            { label: 'BWF Oceania Championships', value: 'BWF Oceania Championships' },
            { label: 'BWF Junior World Championships', value: 'BWF Junior World Championships' },
            { label: 'BWF World Junior Mixed Team Championships', value: 'BWF World Junior Mixed Team Championships' },
        ]
    },
    {
        label: 'Snooker', league: [
            { label: 'World Snooker Tour', value: 'World Snooker Tour' },
            { label: 'World Snooker Championship', value: 'World Snooker Championship' },
            { label: 'UK Championship', value: 'UK Championship' },
            { label: 'Masters', value: 'Masters' },
            { label: 'European Masters', value: 'European Masters' },
            { label: 'China Open', value: 'China Open' },
            { label: 'Welsh Open', value: 'Welsh Open' },
            { label: 'Scottish Open', value: 'Scottish Open' },
            { label: 'Northern Ireland Open', value: 'Northern Ireland Open' },
            { label: 'German Masters', value: 'German Masters' },
            { label: 'English Open', value: 'English Open' },
            { label: 'International Championship', value: 'International Championship' },
            { label: 'Shanghai Masters', value: 'Shanghai Masters' },
            { label: 'World Cup of Snooker', value: 'World Cup of Snooker' },
            { label: 'World Seniors Tour', value: 'World Seniors Tour' },
            { label: 'World Women\'s Snooker Tour', value: 'World Women\'s Snooker Tour' },
            { label: 'World Under-21 Snooker Championship', value: 'World Under-21 Snooker Championship' },
            { label: 'World Amateur Snooker Championship', value: 'World Amateur Snooker Championship' },
            { label: 'International Billiards and Snooker Federation (IBSF)', value: 'International Billiards and Snooker Federation' },

        ]
    },
    {
        label: 'Darts', league: [
            { label: 'PDC World Darts Championship', value: 'PDC World Darts Championship' },
            { label: 'PDC Premier League Darts', value: 'PDC Premier League Darts' },
            { label: 'PDC World Matchplay', value: 'PDC World Matchplay' },
            { label: 'PDC UK Open', value: 'PDC UK Open' },
            { label: 'PDC European Championship', value: 'PDC European Championship' },
            { label: 'PDC Grand Slam of Darts', value: 'PDC Grand Slam of Darts' },
            { label: 'PDC Players Championship Finals', value: 'PDC Players Championship Finals' },
            { label: 'BDO World Darts Championship', value: 'BDO World Darts Championship' },
            { label: 'BDO World Trophy', value: 'BDO World Trophy' },
            { label: 'BDO World Masters', value: 'BDO World Masters' },
            { label: 'WDF World Darts Championship', value: 'WDF World Darts Championship' },
            { label: 'WDF Europe Cup', value: 'WDF Europe Cup' },
            { label: 'WDF Americas Cup', value: 'WDF Americas Cup' },
            { label: 'WDF Asia-Pacific Cup', value: 'WDF Asia-Pacific Cup' },
            { label: 'WDF World Cup', value: 'WDF World Cup' },
            { label: 'PDC Asian Tour', value: 'PDC Asian Tour' },
            { label: 'PDC Development Tour', value: 'PDC Development Tour' },
            { label: 'PDC Challenge Tour', value: 'PDC Challenge Tour' },
            { label: 'PDC World Series of Darts', value: 'PDC World Series of Darts' },
            { label: 'PDC Nordic and Baltic Tour', value: 'PDC Nordic and Baltic Tour' },
            { label: 'PDC South African Tour', value: 'PDC South African Tour' },
            { label: 'PDC North American Tour', value: 'PDC North American Tour' },

        ]
    },
    {
        label: 'Cycling', league: [
            { label: 'Tour de France', value: 'Tour de France' },
            { label: 'Giro d\'Italia', value: 'Giro d\'Italia' },
            { label: 'Vuelta a España', value: 'Vuelta a España' },
            { label: 'UCI Road World Championships', value: 'UCI Road World Championships' },
            { label: 'UCI Track Cycling World Championships', value: 'UCI Track Cycling World Championships' },
            { label: 'UCI Mountain Bike World Championships', value: 'UCI Mountain Bike World Championships' },
            { label: 'UCI Cyclo-cross World Championships', value: 'UCI Cyclo-cross World Championships' },
            { label: 'UCI BMX World Championships', value: 'UCI BMX World Championships' },
            { label: 'UCI Para-cycling Road World Championships', value: 'UCI Para-cycling Road World Championships' },
            { label: 'UCI Para-cycling Track World Championships', value: 'UCI Para-cycling Track World Championships' },
            { label: 'UCI Para-cycling Mountain Bike World Championships', value: 'UCI Para-cycling Mountain Bike World Championships' },
            { label: 'UCI Para-cycling Cyclo-cross World Championships', value: 'UCI Para-cycling Cyclo-cross World Championships' },
            { label: 'UCI Para-cycling BMX World Championships', value: 'UCI Para-cycling BMX World Championships' },
            { label: 'UCI Women\'s WorldTour', value: 'UCI Women\'s WorldTour' },
            { label: 'UCI Men\'s WorldTour', value: 'UCI Men\'s WorldTour' },
            { label: 'UCI Continental Circuits', value: 'UCI Continental Circuits' },
            { label: 'UCI Gran Fondo World Series', value: 'UCI Gran Fondo World Series' },
            { label: 'UCI Para-cycling World Cup', value: 'UCI Para-cycling World Cup' },
            { label: 'UCI Track Cycling World Cup', value: 'UCI Track Cycling World Cup' },
            { label: 'UCI Mountain Bike World Cup', value: 'UCI Mountain Bike World Cup' },
            { label: 'UCI Cyclo-cross World Cup', value: 'UCI Cyclo-cross World Cup' },
            { label: 'UCI BMX Supercross World Cup', value: 'UCI BMX Supercross World Cup' },
        ]
    },
    {
        label: 'Athletics', league: [
            { label: 'IAAF World Championships', value: 'IAAF World Championships' },
            { label: 'Olympic Games Athletics', value: 'Olympic Games Athletics' },
            { label: 'Diamond League', value: 'Diamond League' },
            { label: 'IAAF World Indoor Championships', value: 'IAAF World Indoor Championships' },
            { label: 'IAAF World Cross Country Championships', value: 'IAAF World Cross Country Championships' },
            { label: 'IAAF World Half Marathon Championships', value: 'IAAF World Half Marathon Championships' },

        ]
    },
    {
        label: 'Swimming', league: [
            { label: 'FINA World Championships', value: 'FINA World Championships' },
            { label: 'Olympic Games Swimming', value: 'Olympic Games Swimming' },
            { label: 'FINA World Cup', value: 'FINA World Cup' },
            { label: 'FINA Swimming World Cup', value: 'FINA Swimming World Cup' },
            { label: 'FINA Diving World Series', value: 'FINA Diving World Series' },
            { label: 'FINA Water Polo World League', value: 'FINA Water Polo World League' },
            { label: 'FINA Artistic Swimming World Series', value: 'FINA Artistic Swimming World Series' },
            { label: 'FINA Open Water Swimming World Cup', value: 'FINA Open Water Swimming World Cup' },
            { label: 'FINA High Diving World Series', value: 'FINA High Diving World Series' },
            { label: 'FINA Swimming World Cup Series', value: 'FINA Swimming World Cup Series' },
            { label: 'FINA Diving Grand Prix', value: 'FINA Diving Grand Prix' },
            { label: 'FINA Water Polo World Cup', value: 'FINA Water Polo World Cup' },
            { label: 'FINA Artistic Swimming World Cup', value: 'FINA Artistic Swimming World Cup' },
            { label: 'FINA Open Water Swimming Grand Prix', value: 'FINA Open Water Swimming Grand Prix' },
            { label: 'FINA High Diving World Cup', value: 'FINA High Diving World Cup' },

        ]
    },
    {
        label: 'Other', league: [
            { label: 'Other Sports', value: 'Other Sports' },
            { label: 'Water Polo', value: 'Water Polo' },
            { label: 'Lacrosse', value: 'Lacrosse' },
            { label: 'Field Hockey', value: 'Field Hockey' },
            { label: 'Rugby Sevens', value: 'Rugby Sevens' },
            { label: 'Futsal', value: 'Futsal' },
            { label: 'Handball', value: 'Handball' },
            { label: 'Ultimate Frisbee', value: 'Ultimate Frisbee' },
            { label: 'Bandy', value: 'Bandy' },
            { label: 'Curling', value: 'Curling' },
            { label: 'Skiing', value: 'Skiing' },
            { label: 'Snowboarding', value: 'Snowboarding' },
            { label: 'Surfing', value: 'Surfing' },
            { label: 'Skateboarding', value: 'Skateboarding' },
            { label: 'Rock Climbing', value: 'Rock Climbing' },
            { label: 'Martial Arts', value: 'Martial Arts' },
            { label: 'Gymnastics', value: 'Gymnastics' },
            { label: 'Equestrian', value: 'Equestrian' },
            { label: 'Sailing', value: 'Sailing' },
            { label: 'Rowing', value: 'Rowing' },
            { label: 'Canoeing', value: 'Canoeing' },
            { label: 'Kayaking', value: 'Kayaking' },
            { label: 'Triathlon', value: 'Triathlon' },
            { label: 'Badminton', value: 'Badminton' },
            { label: 'Table Tennis', value: 'Table Tennis' },
            { label: 'Squash', value: 'Squash' },
            { label: 'Cricket', value: 'Cricket' },
            { label: 'Baseball', value: 'Baseball' },
            { label: 'Softball', value: 'Softball' },
            { label: 'Golf', value: 'Golf' },
            { label: 'Motorsport', value: 'Motorsport' },
            { label: 'Esports', value: 'Esports' },
            { label: 'Cycling', value: 'Cycling' },
            { label: 'Athletics', value: 'Athletics' },
            { label: 'Swimming', value: 'Swimming' },
            { label: 'Darts', value: 'Darts' },
            { label: 'Snooker', value: 'Snooker' },
            { label: 'Boxing', value: 'Boxing' },
            { label: 'Mixed Martial Arts', value: 'Mixed Martial Arts' },
            { label: 'Wrestling', value: 'Wrestling' },
            { label: 'Archery', value: 'Archery' },
            { label: 'Shooting', value: 'Shooting' },
            { label: 'Fencing', value: 'Fencing' },
            { label: 'Judo', value: 'Judo' },
            { label: 'Taekwondo', value: 'Taekwondo' },
            { label: 'Karate', value: 'Karate' },
            { label: 'Kickboxing', value: 'Kickboxing' },
            { label: 'Muay Thai', value: 'Muay Thai' },
            { label: 'Billiards', value: 'Billiards' },
            { label: 'Pool', value: 'Pool' },
            { label: 'Bowling', value: 'Bowling' },
            { label: 'Luge', value: 'Luge' },
            { label: 'Skeleton', value: 'Skeleton' },
            { label: 'Bobsleigh', value: 'Bobsleigh' },
            { label: 'Speed Skating', value: 'Speed Skating' },
            { label: 'Figure Skating', value: 'Figure Skating' },
            { label: 'Short Track Speed Skating', value: 'Short Track Speed Skating' },
            { label: 'Curling', value: 'Curling' },
            { label: 'Ice Dancing', value: 'Ice Dancing' },
            { label: 'Synchronized Swimming', value: 'Synchronized Swimming' },
            { label: 'Water Skiing', value: 'Water Skiing' },
            { label: 'Wakeboarding', value: 'Wakeboarding' },
            { label: 'Kiteboarding', value: 'Kiteboarding' },
            { label: 'Paragliding', value: 'Paragliding' },
            { label: 'Hang Gliding', value: 'Hang Gliding' },
        ]
    }
]

export const predictionFormSchema: SchemaDefinition<PredictionFormData> = {
    sportType: {
        type: 'select',
        label: 'Type of Sport',
        required: true,
        placeholder: 'Select a sport type',
        options: [
            { label: 'Soccar', value: 'Soccar' },
            { label: 'Basketball', value: 'Basketball' },
            { label: 'Tennis', value: 'Tennis' },
            { label: 'American Football', value: 'American Football' },
            { label: 'Baseball', value: 'Baseball' },
            { label: 'Hockey', value: 'Hockey' },
            { label: 'Rugby', value: 'Rugby' },
            { label: 'Cricket', value: 'Cricket' },
            { label: 'Volleyball', value: 'Volleyball' },
            { label: 'Handball', value: 'Handball' },
            { label: 'Mixed Martial Arts', value: 'Mixed Martial Arts' },
            { label: 'Boxing', value: 'Boxing' },
            { label: 'Golf', value: 'Golf' },
            { label: 'Motorsport', value: 'Motorsport' },
            { label: 'Esports', value: 'Esports' },
            { label: 'Table Tennis', value: 'Table Tennis' },
            { label: 'Badminton', value: 'Badminton' },
            { label: 'Snooker', value: 'Snooker' },
            { label: 'Darts', value: 'Darts' },
            { label: 'Cycling', value: 'Cycling' },
            { label: 'Athletics', value: 'Athletics' },
            { label: 'Swimming', value: 'Swimming' },
            { label: 'Other', value: 'Other' }
        ],
    },
    league: {
        type: 'select',
        label: 'League',
        required: true,
        placeholder: 'Select a league',
        options: []


    },
    homeTeam: {
        type: 'text',
        label: 'Home Team',
        required: true,
        placeholder: 'Enter home team name',
        validation: {
            minLength: 2,
            maxLength: 100,
        },
    },
    awayTeam: {
        type: 'text',
        label: 'Away Team',
        required: true,
        placeholder: 'Enter away team name',
        validation: {
            minLength: 2,
            maxLength: 100,
        },
    },
    tip: {
        type: 'text',
        label: 'Prediction',
        required: true,
        placeholder: 'Enter your prediction (e.g., Home Win, Draw, Away Win)',
        validation: {
            minLength: 2,
            maxLength: 100,
        },
    },
    odds: {
        type: 'number',
        label: 'Odds',
        placeholder: 'Enter odds for the prediction',
        validation: {
            min: 1,
            max: 1000,
        },
    },
    analysis: {
        type: 'textarea',
        label: 'Analysis',
        placeholder: 'Enter your analysis for the prediction',
        validation: {
            maxLength: 2000,
        },
    },
    publishedAt: {
        type: 'datetime-local',
        label: 'Match Date',
        placeholder: 'Select publication date and time',
        required: true,

    },
    isFree: {
        type: 'checkbox',
        label: 'Free Prediction',


    },
    isCustom: {
        type: 'checkbox',
        label: 'Custom Prediction (e.g. bet of the day, correct score, draw games,..)',
        required: false,
    },

    customTitle: {
        type: 'select',
        label: 'Game prediction type (title can be changed)',
        required: true,
        placeholder: 'Select a custom',
        options: [
           
        ],
    },

    result: {
        type: 'select',
        label: 'Result',
        options: [
            { label: 'Pending', value: PredictionResult.PENDING },
            { label: 'Won', value: PredictionResult.WON },
            { label: 'Lost', value: PredictionResult.LOST },
        ],
    },

    userId: {
        type: 'text',
        label: 'User ID',
        placeholder: 'Enter user ID',
        required: true,
        disabled: true,
        hidden: true,
    }
};
